// DTOs/PatientDTOs.cs
using System.ComponentModel.DataAnnotations;

namespace backend.DTOs
{
    public class PatientDto
    {
        public Guid Id { get; set; }
        public string FullName { get; set; } = string.Empty;
        public DateOnly DateOfBirth { get; set; }
        public string Gender { get; set; } = string.Empty;
        public string? Email { get; set; }
        public string? Phone { get; set; }

        public string PatientID { get; set; } = string.Empty;

    }

    public class CreatePatientDto
    {
        // No Id here, as it's generated by the backend/DB
        [Required(ErrorMessage = "Full Name is required.")]
        [StringLength(100, ErrorMessage = "Full Name cannot exceed 100 characters.")]
        public string FullName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Date of Birth is required.")]
        public DateOnly DateOfBirth { get; set; }

        [Required]
        [StringLength(20)]
        public string Gender { get; set; } = string.Empty;

        [StringLength(200)]
        public string? Email { get; set; }

        [StringLength(200)]
        public string? Phone { get; set; }

        [StringLength(200)]
        public string? MedicalHistory { get; set; }

    }

    public class UpdatePatientDto
    {
        [StringLength(100, ErrorMessage = "Full Name cannot exceed 100 characters.")]
        public string? FullName { get; set; } // Nullable if updates are partial

        public DateOnly? DateOfBirth { get; set; }

        [StringLength(20, ErrorMessage = "Gender cannot exceed 20 characters.")]
        public string? Gender { get; set; }

        [StringLength(200)]
        public string? Email { get; set; }

        [StringLength(200)]
        public string? Phone { get; set; }

        [StringLength(200)]
        public string? MedicalHistory { get; set; }

    }
}
